services:
  - type: web
    name: diabetes-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    repo: https://github.com/Longman-max/Diabetes-Predictor.git
    branch: main
    autoDeploy: true
